### ISSUE TITLE
Revisión de anagrama

### ISSUE THREAD

**Issue by ericksc** [kearve/PythonBasico#2]
https://github.com/kearve/PythonBasico/blob/397df514440eb4ae54161425cef88e40ff2b71da/palindromo.py#L1

funciona perfectamente

![image](https://user-images.githubusercontent.com/20059518/52151447-c06e7800-2638-11e9-898a-e5812fc6a77d.png)

**Comment by kearve** [comment]
perfecto, gracias

**Comment by kearve** [comment]
perfecto, gracias
