### ISSUE TITLE
revision de tarea 1

### ISSUE THREAD

**Issue by ericksc** [kearve/PythonBasico#3]
https://github.com/kearve/PythonBasico/blob/397df514440eb4ae54161425cef88e40ff2b71da/tarea_1/tarea_1.py#L1

Funciona perfectamente

![image](https://user-images.githubusercontent.com/20059518/52151486-dda34680-2638-11e9-9fa6-0f8c2f3eadc0.png)

**Comment by kearve** [comment]
perfecto, gracias
