### ISSUE TITLE
Revisión de tarea 2

### ISSUE THREAD

**Issue by ericksc** [kearve/PythonBasico#4]
https://github.com/kearve/PythonBasico/blob/397df514440eb4ae54161425cef88e40ff2b71da/tarea_2/calculo_Lista.py#L1

Funciona perfectamente. Puedes revisar la wiki del curso para las recomendaciones.

Tu solución esta bien. es limpia y directa.

![image](https://user-images.githubusercontent.com/20059518/52151543-0b888b00-2639-11e9-9dda-cfea676fd859.png)

**Comment by kearve** [comment]
Ok perfecto, gracias profe
